"""crear tablas de usuarios y roles

Revision ID: d8eb83c0426b
Revises: 1c39be2955e7
Create Date: 2026-06-25 20:43:55.123253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8eb83c0426b'
down_revision = '1c39be2955e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materia_prima')
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('personal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('rol', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('celular', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('materia_prima',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cantidad', mysql.FLOAT(), nullable=False),
    sa.Column('unidad', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('referenciaColor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
